### ISSUE TITLE
BloomFilter.h: No such file or directory

### ISSUE THREAD

**Issue by holdsworth** [bbondy/abp-filter-parser-cpp#28]
make: Entering directory `/path/to/node/node_modules/abp-filter-parser-cpp/build'
  CXX(target) Release/obj.target/abp-filter-parser-cpp/addon.o
In file included from ../ABPFilterParser.h:9:0,
                 from ../ABPFilterParserWrap.h:12,
                 from ../addon.cpp:7:
.././filter.h:12:25: fatal error: BloomFilter.h: No such file or directory
 #include "BloomFilter.h"
                         ^
compilation terminated.

**Comment by holdsworth** [comment]
So I compiled the repo, afterwards I moved the folder(abp-filter-parser-cpp) to my project's node_modules/ folder and when I tried to run my script I received an error that says, no such module as abp-filter-parser-cpp

i had to insert a .npmignore file to the repo install other modules with npm.

**Comment by holdsworth** [comment]
after continuous retries I got this

/path/to/script.js:34
ABPFilterParser.parse(easyListTxt, parsedFilterData);
                ^

TypeError: ABPFilterParser.parse is not a function
    at Object.<anonymous> (/path/to/script.js:34:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by snyderp** [comment]
@holdsworth are you still seeing this?  Otherwise, will close out since I can't reproduce
